language: rust
rust:
- stable
cache: cargo
install:
  - cargo install cargo-audit
jobs:
  include:
  - stage: audit
    script:
      - cargo audit
  - stage: unittest
    script:
    - cargo build --verbose
    - cargo test --verbose
notifications:
  email:
    on_success: never